"""Módulo de configuración del proyecto hm-recsys-mvalvar."""

from config.settings import (
    AGE_BIN_LABELS,
    AGE_BINS,
    BASE_DIR,
    DATA_PROCESSED_DIR,
    DATA_RAW_DIR,
    DATA_SAMPLE_DIR,
    FIGURES_DIR,
    LAMBDA_DECAY,
    LGBM_PARAMS,
    LGBM_SAMPLE_PARAMS,
    MEMORIA_DIR,
    METRIC_EVAL_K,
    MODELS_DIR,
    N_CANDIDATES_PER_USER,
    NEGATIVE_RATIO,
    RANDOM_SEED,
    RESULTS_DIR,
    TABLES_DIR,
    TEMPORAL_WINDOW_WEEKS,
    USE_SAMPLE_DATA,
    VAL_WINDOW_DAYS,
    get_active_data_dir,
)

__all__ = [
    "BASE_DIR",
    "DATA_RAW_DIR",
    "DATA_SAMPLE_DIR",
    "DATA_PROCESSED_DIR",
    "MODELS_DIR",
    "RESULTS_DIR",
    "FIGURES_DIR",
    "TABLES_DIR",
    "MEMORIA_DIR",
    "USE_SAMPLE_DATA",
    "get_active_data_dir",
    "TEMPORAL_WINDOW_WEEKS",
    "VAL_WINDOW_DAYS",
    "N_CANDIDATES_PER_USER",
    "NEGATIVE_RATIO",
    "LGBM_PARAMS",
    "LGBM_SAMPLE_PARAMS",
    "AGE_BINS",
    "AGE_BIN_LABELS",
    "LAMBDA_DECAY",
    "RANDOM_SEED",
    "METRIC_EVAL_K",
]
